folke/which-key.nvim

- README.md
- lua/which-key/config.lua
- lua/which-key/keys.lua
- lua/which-key/text.lua
The default view is a bit compact, and even after configurating it a bit wider, many longer strings are shortened to an illisible "...", which kind of defeats the purpose of which-keys...
(consider one of my own mapping : `nnoremap <silent> <leader>a <cmd>lua require('lspsaga.codeaction').code_action()<CR>`, not saying it's best pratice but many users' may look like this)
This should help a little bit, by removing the standard boilerplate cluttering the mappings.
Probably not an exhaustive list, but this should be 'safe', ie not remove any substring that is an important part to understanding what the mapping do
> hide mapping boilerplate

- lua/which-key/plugins/registers.lua
without the '1' the register gets evaluated and I get
'Vim(call):E474: Invalid argument'.
From vim documentation:
getreg('=') returns the last evaluated value of the expression
register.  (For use in maps.)
getreg('=', 1) returns the expression itself, so that it can
be restored with |setreg()|.  For other registers the extra
argument is ignored, thus you can always give it.
> fix: get value of register '=' with getreg('=',1)

- lua/which-key/util.lua
- lua/which-key/view.lua
`CTRL-O` is fed again if mode is `niI`, `niR`, `niV`, `vs`, `Vs`, `CTRL-Vs`.
`vs`, `Vs`, `CTRL-Vs` have just been ported to Neovim (<https://github.com/neovim/neovim/pull/15213>).
> fix: feed CTRL-O again if called from CTRL-O

- lua/which-key/keys.lua
This is the only issue I've run into when using the new `nvim_{buf_}set_keymap` functions added recently. Not sure if there is a cleaner way to fix it, but essentially we can no longer rely on the mappings having a `rhs` (as returned from `nvim_{buf_}get_keymap`) if they instead define a `callback` as part of the `opts` key.
This is the only place where I can see that this API function is used.
Fixes #224
> Handle nvim_{buf_}get_keymap return no rhs due to 'callback' mapping

- README.md
Two links to sections of the source code seem to point to an (afaict) arbitrary commit, rather than to the main-branch version of the file. Another link to the same file _does_ point to the main-branch version of the file, which makes me think that this would be the intended state for all the links.
Thankfully the file didn't change much in the meantime, so the line-references are still accurate in either version.
> Point all links in README to main branch

- lua/which-key/config.lua
- lua/which-key/init.lua
- lua/which-key/keys.lua
- lua/which-key/layout.lua
- lua/which-key/tree.lua
- lua/which-key/types.lua
- lua/which-key/util.lua
- lua/which-key/view.lua
Fix #121
Fix #178
Fix #199
Fix #254
Fix #274
Fix #277
Internal keycodes and key notations need to be parsed differently. The `prefix` variable name is very confusing, as it is used for two purposes.
> Fix prefix

- README.md
- lua/which-key/keys.lua
- lua/which-key/types.lua
It obviously makes more sense to use the built-in description as the default label, which even eliminates a lot of repetition of `require('which-key').register ... `
> feat: prefer `desc` to `cmd` as the fallback label

- lua/which-key/keys.lua
When a keymap has `!` on the left-hand side and an anonymous function on the right-hand side, mapargs returns a table with no `rhs`, which breaks the test against `cmd`. This only seems to be an issue for this specific `lhs` value.
This PR is a simple fix: it checks to make sure `rhs` exists before testing against `cmd`.
> Fix mapping when right-hand side is `nil`

- README.md
- lua/which-key/colors.lua
The name of highlighting group is [`DiffAdd`](https://neovim.io/doc/user/syntax.html#hl-DiffAdd), not `DiffAdded`
> fix(colors): Separator links to DiffAdd

- lua/which-key/view.lua
fixes https://github.com/folke/which-key.nvim/issues/115 
hack but works.  The underlying problem is caused by which-key popup, which invalidates visual-multi state. This PR checks if before opening WKey popup we were in Visual-multi-mode, if so, then reapply last visual multi state - vim.cmd[[normal \\gS]]
> Compatibility with Vim Visual Multi plugin

- lua/which-key/plugins/presets/misc.lua
It seems like we are missing `<C-w>_`.
> Add description of <C-w>_

- lua/which-key/view.lua
Fix https://github.com/folke/which-key.nvim/issues/202
Please let me know if there is anything I can do/add to the PR to help out. Love this plugin, thanks in advance!
> Reset `+` and `*` to default register when clipboard is set

- lua/which-key/view.lua
Otherwise "gg" cannot open a fold when which-key.nvim is used even if
"jump" flags is in 'foldopen'.
> fix: feed the keys as typed

- lua/which-key/keys.lua
Fix #249
Now `Util.t()` is applied to the string passed to `string.format()`,
replacing of leader is no longer needed because `Util.t()` will replace
it. Replacing a backslash with `<bslash>` breaks `<C-\>` mappings, and
it isn't needed either.
> fix: remove unnecessary replacement of backslash

- lua/which-key/keys.lua
It would be very convenient to be able to hide a mapping using its `desc` attribute.
> Hide mapping when `desc = "which_key_ignore"`

- README.md
I've added a link in "❗️ IMPORTANT" note, to highlight that timeout is a vim option and not a generic word.
Also added it to config examples. 
Maybe it's only me, but I missed it while reading the documentation, and spend some time wondering why it's not working. Nearly uninstalled plugin lol :D
> README.md: timeout link and config examples

- lua/which-key/mappings.lua
Profiling with perfanno.nvim shows that a large portion of startup time was spent on this line due to the computation of the error string.
This commit avoids computing the problematic error string unless it is going to be raised.
Startup time as recorded by lazy.nvim shows a reduction of 28% with this change: 13.43ms -> 10.49ms.
> perf(mappings): avoid computing error string on hot path

- lua/which-key/util.lua
Rewrite the notation and internal key parsers into state machine and apply common Lua optimizations.
The result is a net startup time improvement of ~13.2%: 11.3ms[+-0.156] -> 9.81ms[+-0.165] (10 samples).
See the commit messages within this PR for more information on the optimizations applied.
> refactor(util): simplify and optimize parsers

- lua/which-key/util.lua
neovim is very lenient on the parsing of `<` in mappings. If the `<>` pairs did not enclose a valid special key, the entire sequence will be treated as `<lt>[keys here]>`.
To handle this, simply cross reference against the internal representation to see if the key should be treated as a special key.
Ref https://github.com/folke/which-key.nvim/pull/435#issuecomment-1510488159
> fix(util): only collect valid <> keys

- lua/which-key/layout.lua
This PR allows the use of deviating paddings per side.
Currently, it won't work to set another padding for top then for bottom for example. It also cleans up variables a bit.
Here are some screenshots:
Adding padding top has no effect:
Changing padding bot changes both:
Allowing deviating values, e.g. top = 1, bot = 0 works quite nice with cmdheight = 0. Looks uniform.
Please let me know about desired changes and feel free to modify the PR.
> fix: allow deviating paddings per side

- lua/which-key/keys.lua
This PR fixes the issue https://github.com/folke/which-key.nvim/issues/368.
Currently, if no errors are found, check health does not display any concluding message.
This PR adds a simple OK message when no conflicting keymaps are found.
> Add OK output to check_health fn

- README.md
- lua/which-key/config.lua
- lua/which-key/view.lua
Ensure the which-key window appears above other floating windows, 
such as the LSP diagnostics or terminal that floats.
This improves visibility when using the which-key plugin.
> feat(view): ensure it's above other floating windows

- README.md
There's a small spelling mistake & this PR provides a fix for it. The correct `:checkhealth` command should be `:checkhealth which-key` and not `:checkhealth which_key`
> Fix a minor spelling mistake with the checkhealth command

- .github/ISSUE_TEMPLATE/bug_report.yml
When creating #488, I noticed that the `repro.lua` template was missing the actual configuration call for the plugin.
> Add `config  = true` to issue template

- lua/which-key/plugins/presets/init.lua
This fixes a small typo in the description of the `!` operator.
> fix: small typo in operator description

- lua/which-key/mappings.lua
There are two patterns of adding a description, with a second string or with the `desc` key.
Legendary.nvim uses the `parse` function from which-key. This function does not check the `desc` key in the table, which should be supported.
> feat(mappings): check if `desc` key exists when parsing mappings

- lua/which-key/view.lua
IMHO we can disable whichkey since cmdline-window is restricted.
> fix(is_enabled): disable whichkey in cmdline-window

- lua/which-key/keys.lua
Fix #355. I tested this locally and it works like a charm.
> Credit goes to @liujoey who opened the original MR https://github.com/folke/which-key.nvim/pull/356.
> fix(ignore_missing): not showing key maps with desc field

- lua/which-key/keys.lua
- lua/which-key/view.lua
* User can now use keymaps with <nop> to set `desc` as label to prefix
key
* Fix some typo
**Example**:
```lua
...
map("n", "<leader>h", "<Nop>", {desc = "Help Prefix"})
map("n", "<leader>p", "<Nop>", {desc = "Projects Prefix"})
map("n", "<leader>f", "<Nop>", {desc = "File Prefix"})
map("n", "<leader>b", "<Nop>", {desc = "Buffer Prefix"})
map("n", "<leader>c", "<Nop>", {desc = "Coding Prefix"})
map("n", "<leader>g", "<Nop>", {desc = "Git Prefix"})
map("n", "<leader>d", "<Nop>", {desc = "Diagnostic Prefix"})
map("n", "<leader>t", "<Nop>", {desc = "Toggle & Setting Prefix"})
...
```
> feat(keys): `desc` in <nop> keymaps can now become prefix label

- lua/which-key/plugins/spelling.lua
Standard vim and vanilla neovim both blackhole z= replaced words
This makes the behaviour more like a vanilla z= as you don't end up with the misspelt word in your register
> fix: black hole z= replacements

- lua/which-key/view.lua
problem: as of neovim/neovim#24824 buf_set_lines adjusts topline differently, which breaks scrolling in the which-key menu. See the discussion in that PR for more info.
solution: save and restore view when rendering to ensure that the render does not change scroll position.
fixes #515
> fix(scroll): restore win view after rendering buffer

- lua/which-key/keys.lua
If there are nested operators defined (i.e. two operators share the same prefix), for example, when using `nvim-surround`, the operators could be:
```lua
config.operators = {
y = "Yank",
yz = "Add surrounding",
}
```
Currently, `which-key.keys.get_operator()` loops through all defined operators and selects the first one that is a prefix of `prefix_i`. However, the order of iteration is random, which means if `prefix_i = "yz"`, it could return either `y` or `yz`. If `y` is returned, `prefix_i` is split into `y` and a subsequent `z`, thus `yz` won't be shown as an operator.
This PR changes the `get_operator()` implementation to return the longest defined operator.
> fix: support nested operators

- lua/which-key/mappings.lua
Old versions of which-key.nvim use `vim.api.nvim_set_keymap()`, which has `replace_keycodes` always default to `false`.
The new version of which-key.nvim uses `vim.keymap.set()`, which has `replace_keycodes` default to `true` if `expr` is `true`.
To not break old specs, make `replace_keycodes` default to `false` there.
> fix(mappings): make replace_keycodes default to false in v1 spec

- lua/which-key/types.lua
Fix spec field types for [1] lhs and [2] rhs, as documented in README.
> fix(types): spec field types

- lua/which-key/view.lua
As you can see from the screenshot below, this appears to fix things. Have tested on both nvim stable (v.0.10.0) and nightly, results are identical now. 
Fixes #683
Result:
> fix(view): ensure highlights get set for title padding

- lua/which-key/view.lua
A minor fix for the format function, which wasn't working correctly for keymaps that include 3 or more keys - see screenshots.
(order is different because of sorting)
> fix(view): fix format for keymaps with 3+ keys

- lua/which-key/icons.lua
Added frontier pattern for `ai` as it matches on words such as `pair` and probably others as well.
> fix(icons): added frontier pattern for `ai`

- README.md
- doc/which-key.nvim.txt
- lua/which-key/config.lua
> fix(typo): change 'explicitely' to 'explicitly' in docs

- lua/which-key/view.lua
The footer section of WhichKey window displays help for built-in keys (Esc, BS, scroll up and down). The scroll keys are configurable, however the help message always displays the hard-coded default values.
> fix(view): display actual scroll up/down keys in help

- doc/which-key.nvim.txt
- lua/which-key/config.lua
Which-key by default is disable in insert mode and command mode in order to not conflict with typing. This logic also applies to terminal mode which is a special type of "insert" like mode
> fix(config): disable wk by default  for terminal mode

- lua/which-key/state.lua
Fix the spelling in an error message from instad to instead
> fix(typo): error message spelling of instad to instead

- lua/which-key/icons.lua
This adds a default icon for [grapple.nvim](https://github.com/cbochs/grapple.nvim)
> feat(icons): add grapple icon

- lua/which-key/health.lua
Fixes a small capitalisation typo :)
Thanks for the great plugin!
> docs: typo
